# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\TeamInsepet\NSX-Prime\Hardware\CorEx-MUX-Kernel-Enhanced\Workspace01\CorEx-Mux-Kernel.cydsn\CorEx-Mux-Kernel.cyprj
# Date: Fri, 28 Apr 2017 12:01:52 GMT
#set_units -time ns
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 16.666666666666664 -waveform {0 8.33333333333333} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 16.666666666666664 -waveform {0 8.33333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_clock -name {CyBUS_CLK(fixed-function)} -period 16.666666666666664 -waveform {0 8.33333333333333} [get_pins {ClockBlock/clk_bus_glb_ff}]
create_generated_clock -name {timer_clock_1} -source [get_pins {ClockBlock/clk_sync}] -edges {1 61 121} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_clock -name {timer_clock_1(fixed-function)} -period 1000 -waveform {0 16.6666666666667} [get_pins {ClockBlock/dclk_glb_ff_0}]
create_generated_clock -name {timer_clock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 61 121} [list [get_pins {ClockBlock/dclk_glb_1}]]
create_generated_clock -name {Display2_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 131 261} [list [get_pins {ClockBlock/dclk_glb_2}]]
create_generated_clock -name {Display1_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 131 261} [list [get_pins {ClockBlock/dclk_glb_3}]]
create_generated_clock -name {Clock_Printer} -source [get_pins {ClockBlock/clk_sync}] -edges {1 781 1563} [list [get_pins {ClockBlock/dclk_glb_4}]]
create_generated_clock -name {RF_Physical_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 781 1563} [list [get_pins {ClockBlock/dclk_glb_5}]]
create_generated_clock -name {Clock_Pump} -source [get_pins {ClockBlock/clk_sync}] -edges {1 1303 2605} [list [get_pins {ClockBlock/dclk_glb_6}]]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for C:\TeamInsepet\NSX-Prime\Hardware\CorEx-MUX-Kernel-Enhanced\Workspace01\CorEx-Mux-Kernel.cydsn\TopDesign\TopDesign.cysch
# Project: C:\TeamInsepet\NSX-Prime\Hardware\CorEx-MUX-Kernel-Enhanced\Workspace01\CorEx-Mux-Kernel.cydsn\CorEx-Mux-Kernel.cyprj
# Date: Fri, 28 Apr 2017 12:01:34 GMT
